# Generated by Django 2.1.2 on 2019-01-10 10:06

from django.db import migrations, models
import django.db.models.deletion
import watch.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_episodes', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('season_number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cast', models.CharField(blank=True, max_length=1000, null=True)),
                ('synopsis', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('voters_of_rating', models.IntegerField(blank=True, null=True)),
                ('date_of_release', models.DateField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('running_time', models.IntegerField()),
                ('number_of_seasons', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Series',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_quality', models.CharField(choices=[('144', '144p'), ('240', '240p'), ('360', '360p'), ('720', '720p'), ('1080', '1080p')], max_length=4)),
                ('length', models.IntegerField(blank=True, help_text='enter in seconds', null=True)),
                ('intro_start', models.IntegerField(blank=True, help_text='enter in seconds', null=True)),
                ('intro_end', models.IntegerField(blank=True, help_text='Enter in seconds', null=True)),
                ('credits_start', models.IntegerField(blank=True, help_text='Enter in seconds', null=True)),
                ('video_art', models.ImageField(blank=True, null=True, upload_to='watch/art')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='watch.Video')),
                ('episode_number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=watch.models.upload_episode_to)),
            ],
            bases=('watch.video',),
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='watch.Video')),
                ('title', models.CharField(max_length=100)),
                ('director', models.CharField(blank=True, max_length=400, null=True)),
                ('writers', models.CharField(blank=True, max_length=400, null=True)),
                ('cast', models.CharField(blank=True, max_length=1000, null=True)),
                ('synopsis', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('voters_of_rating', models.IntegerField(blank=True, null=True)),
                ('date_of_release', models.DateField()),
                ('genre', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to=watch.models.upload_movie_to)),
            ],
            bases=('watch.video',),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.Series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watch.Season'),
        ),
    ]
